#!/bin/bash

MOUNT_SOURCES="$HOME/mnt/"
MOUNTABLE_TYPE="/dev/sdb"
DMENU=dmenu
#DMENU=term-dmenu

pgrep -x $DMENU && exit

MOUNTABLEDRIVES=$(lsblk -lp | grep -e "part $" -e $MOUNTABLE_TYPE  | awk '{print $1, "(" $4 ")"}') 
[[ "MOUNTABLEDRIVES" = "" ]] && exit 1
CHOSEN=$(printf "none\n$MOUNTABLEDRIVES" | $DMENU -i -p "mount?" | awk '{print $1}')
[[ "$CHOSEN" = "" ]] && exit 1 || [[ "$CHOSEN" = "none" ]] && exit 1

DIRS=$(find $MOUNT_SOURCES -type d -maxdepth 1 2>/dev/null | grep "/mnt/")
[[ "DIRS" = "" ]] && exit 1
MOUNTPOINT=$(printf "none\n$DIRS" | $DMENU -i -p "where to?")
[[ "$MOUNTPOINT" = "" ]] && exit 1 || [[ "$MOUNTPOINT" = "none" ]] && exit 1
sudo mount $CHOSEN $MOUNTPOINT && echo "mounted $CHOSEN to $MOUNTPOINT, run \"umnt\" to unmount"
