#!/bin/bash

[[ $# -eq 0 ]] && echo "No input" && amixer -D pulse sset Master 0%+ && exit


[[ "$1" == "toggle" ]] && amixer -q -D pulse set Master toggle && exit
[[ "$1" == "mute" ]]   && amixer -q -D pulse set Master mute   && exit
[[ "$1" == "unmute" ]]   && amixer -q -D pulse set Master unmute   && exit

[[ $# -le 1 ]] && echo "No value specified for '$1', specify percentage" && exit

[[ "$1" == "up" ]]     && amixer -D pulse sset Master "$2"%+   && exit
[[ "$1" == "down" ]]   && amixer -D pulse sset Master "$2"%-   && exit
[[ "$1" == "set" ]]   && amixer -D pulse sset Master "$2"%     && exit
